project:
  type: book
  render:
    - "*.qmd"
    - "*.ipynb"
    - "*.md"
    - "!resources/"
    - "!slides/"
  resources:
    - "*.csv"
    - "*.tsv"
    - "*.zip"
    - "*.xlsx"
    - "*.csv.gz"
    - "slides/*.html"
book:
  title: "CIS241 Intro to Data Science"
  sidebar:
    logo: images/startrek.jpg
  chapters:
  - index.qmd
  - part: "Course Information"
    chapters:
    - schedule.qmd
    - policies.md
    - groundrules.md
  - part: assignments.md
    chapters:
      - assignments/documentation.md  
      - assignments/project-planning.md
      - assignments/presentation.md
      - assignments/final-report.md
  - part: "Guides"
    chapters:
      - guides/jupyterhub.md
      - guides/python.ipynb
      - guides/pandas.ipynb
      - guides/altair.ipynb
  - part: "Other Key Info"
    chapters:
    - how-to-explain.ipynb
    - radcat.md
    - sample-final-project.ipynb
    - guides/jupyter.md
  search: false
  navbar:
    right:
      - href: index.qmd
        text: Home
      - schedule.qmd
      - assignments.md
      - policies.md
      - groundrules.md
      - href: https://jupyterhub.ciswashjeff.net/
        text: JupyterHub

format:
  html:
    theme: lumen
    css: styles.css
    toc: true
