project:
  type: website
  render:
    - "*.qmd"
    - "*.ipynb"
    - "*.md"
    - "!resources/"
    - "!slides/"
  resources:
    - "*.csv"
    - "*.tsv"
    - "*.zip"
    - "*.xlsx"
    - "*.csv.gz"
    - "slides/*.html"
website:
  favicon: bar_chart_apple_64.png
  title: "CIS241 Intro to Data Science"
  sidebar:
    logo: images/startrek.jpg
    search: false
    contents:
    - index.qmd
    - section: "Course Information"
      contents:
      - schedule.qmd
      - policies.md
      - criteria.md
      - assignments.md
    - section: "Guides"
      contents:
        - guides/jupyterhub.md
        - guides/python.ipynb
        - guides/pandas.ipynb
        - guides/hypothesis-testing.qmd
        - guides/sklearn.qmd
        - guides/debugging.qmd
    - section: "Other Key Info"
      contents:
      - how-to-explain.ipynb
      - radcat.md
      - guides/uploading.qmd
      - text: "Sample Final Project"
        href: sample-final-project.ipynb
      - guides/jupyter.md
  navbar:
    right:
      - href: index.qmd
        text: Home
      - schedule.qmd
      - assignments.md
      - policies.md
      - href: https://jupyterhub.ciswashjeff.net/
        text: JupyterHub

format:
  html:
    theme: lumen
    css: styles.css
    toc: true
