project:
  type: website

website:
  title: "CIS241 Intro to Data Science"
  navbar:
    right:
      - href: index.qmd
        text: Home
      - schedule.qmd

format:
  html:
    theme: lumen
    css: styles.css
    toc: true



