---
title: "Introduction to Data Science"
subtitle: <a class="btn btn-outline-info" href="schedule.qmd">Schedule</a> <a class="btn btn-outline-info">Assignments</a> <a class="btn btn-outline-info">Course Policies</a> <a class="btn btn-outline-info">Sakai</a> <a class="btn btn-outline-info">JupyterHub</a>
toc: false
title-block-banner: images/startrek.jpg
title-block-banner-color: white
---

::: {.card .border-primary .mb-3}

:::: {.card-body}

CIS 241. Washington & Jefferson College. Spring 2025.

**Meeting Time: TR 9:00-10:45pm**

**Dr. Ladd’s Student Drop-In Hours: MW 10am–12pm TECH 201**  
**or email for appointment, jladd@washjeff.edu**

**PAL Tutoring Hours: 7-10pm Sunday–Thursday in the CIS Lounge (TECH 217)**  
**[Tutor bios and additional info](https://mywj.washjeff.edu/knowledgebase/cis-peer-tutoring/department/computing-and-information-studies)**

::::

:::

## Course Description

From social media to the James Webb telescope, from Shakespeare's plays to the U.S. Census, data is being collected all around us, all the time. How can we make sense of these near-constant streams of information?

This course will attempt to answer this question by introducing the concepts and practices involved in data analysis: data collection and preparation, exploratory analysis, and prediction and classification. Using the programming language Python and other industry-standard tools, we will practice ways of working with data from simple summary statistics to advanced machine learning models. At each step of the way, we'll discuss how to approach data analysis critically and ethically. And we'll explore data sets from a wide range of fields and disciplines, including sociology, ecology, business, film, and history.

## Learning Goals

At the end of this course, you should be able to:

- Understand and implement the data analysis process, from data collection to communicating results.
- Use exploratory data analysis to quickly understand a complex dataset.
- Apply modeling techniques to make predictions.
- Evaluate the effectiveness of different modeling techniques.
- Think and act ethically at all steps of the data analysis process.

<small>Banner image: The Library Computer Access/Retrieval System (LCARS), a fictional operating system and data analysis interface from *Star Trek: The Next Generation*</small>
