---
title: Course Schedule 
toc: false
format:
  html:
    page-layout: full
---

Date|Topics & Slides|Workshops|Assignments|Supplemental Reading
--|---|---|---|---
13 & 15 Jan.|[What Is Data?](slides/whatisdata.html) & Responsible Data Collection|[Jupyter](guides/jupyterhub.md)||Bruce Ch. [1](https://ebookcentral.proquest.com/lib/washjeff/reader.action?docID=6173908&ppg=11&c=RVBVQg)
20 & 22 Jan.|[Python & Data Wrangling](slides/wrangling.html)|0: <a href="resources/00_python_pandas.ipynb" download>Practice Python</a>||McKinney, Ch. [3](https://wesmckinney.com/book/python-builtin), [5](https://wesmckinney.com/book/pandas-basics), and [8](https://wesmckinney.com/book/data-wrangling); Downey Ch. [7](https://allendowney.github.io/ElementsOfDataScience/07_dataframes.html)
27 & 29 Jan.|[Exploratory Data Analysis](slides/eda.html): Summary Statistics & Data Types|1: <a href="resources/01_movies1.ipynb" download>Movies 1</a>|**[Documentation Assignment](assignments/documentation.md) Due 29 Jan.**|Downey Ch. [2](https://allendowney.github.io/ElementsOfDataScience/02_times.html); McKinney Ch. [11](https://wesmckinney.com/book/time-series)
3 & 5 Feb.|Exploratory Data Analysis: [Visualization](slides/visualizing.html)|1: <a href="resources/01_movies2.ipynb" download>Movies 2</a>||Wilke Ch. [5](https://clauswilke.com/dataviz/directory-of-visualizations.html) and UW Ch. [1, 2, 3, & 6](https://idl.uw.edu/visualization-curriculum/intro.html)
10 & 12 Feb.|Hypothesis Testing: [Comparison of Means](slides/hypothesis.html)|2: <a href="resources/02_baseball1.ipynb" download>Sports 1</a>|(Begin Test 1)|Downey Ch. [11](https://allendowney.github.io/ElementsOfDataScience/11_resampling.html) and [13](https://allendowney.github.io/ElementsOfDataScience/13_hypothesis.html); Bruce Ch. [3](https://ebookcentral.proquest.com/lib/washjeff/reader.action?docID=6173908&ppg=83&c=RVBVQg)
17 & 19 Feb.|Hypothesis Testing: [Correlation](slides/correlation.html)|2: <a href="resources/02_baseball2.ipynb" download>Sports 2</a>|**Test 1** 19 Feb.|Downey Ch. [9](https://allendowney.github.io/ElementsOfDataScience/09_relationships.html)
24 & 26 Feb.|Supervised Learning: [Regression](slides/regression.html)|3: <a href="resources/03_airbnb1.ipynb" download>Business 1</a>||Downey Ch. [10](https://allendowney.github.io/ElementsOfDataScience/10_regression.html); McKinney Ch. [12.4](https://wesmckinney.com/book/modeling#modeling-scikit-learn); Bruce Ch. [4](https://ebookcentral.proquest.com/lib/washjeff/reader.action?docID=6173908&ppg=123&c=RVBVQg)
3 & 5 Mar.|Supervised Learning: [Regression, cont.](slides/regression-ml.html)|3: <a href="resources/03_airbnb2.ipynb" download>Business 2</a>||Bruce Ch. [6](https://ebookcentral.proquest.com/lib/washjeff/reader.action?docID=6173908&ppg=208&c=RVBVQg)
17 & 19 Mar.|[Ethical Data Science](slides/ethics.html); Project Meetings|3.5: Ethics|**[Project Plan](assignments/project-planning.md) Due 19 Mar.**|
24 & 26 Mar.|Supervised Learning: [Classification](slides/logit.html)|4: <a href="resources/05_health1.ipynb" download>Health 1</a>||Bruce Ch. [5](https://ebookcentral.proquest.com/lib/washjeff/reader.action?docID=6173908&ppg=171&c=RVBVQg)
31 Mar. & 2 Apr.|Supervised Learning: [Classification, cont.](slides/classification-ml.html); Project Meetings|4: <a href="resources/05_health2.ipynb" download>Health 2</a>|(Begin Test 2)|Bruce Ch. [5](https://ebookcentral.proquest.com/lib/washjeff/reader.action?docID=6173908&ppg=169&c=RVBVQg) & [6](https://ebookcentral.proquest.com/lib/washjeff/reader.action?docID=6173908&ppg=208&c=RVBVQg)
7 & 9 Apr.|Unsupervised Learning: [Clustering](slides/clustering.html)|5: <a href="resources/06_lit1.ipynb" download>Literature 1</a>|**Test 2** 9 Apr.|Bruce Ch. [7](https://ebookcentral.proquest.com/lib/washjeff/reader.action?docID=6173908&ppg=258&c=RVBVQg)
14 & 16 Apr.|Unsupervised Learning: [Dimension Reduction](slides/pca.html)|5: <a href="resources/06_lit2.ipynb" download>Literature 2</a>|**[Video Presentations](assignments/presentation.md) Due 16 Apr.**|Bruce Ch. [7](https://ebookcentral.proquest.com/lib/washjeff/reader.action?docID=6173908&ppg=251&c=RVBVQg)
21 & 23 Apr.|Discuss Projects & Videos, [Sample Final Project](sample-final-project.ipynb)||
28 Apr. **2pm–3:50pm**|CIS Open House on Scholars Day!||**[Final Project](assignments/final-report.md) Due Fri. 1 May at 2pm**

: {.striped .hover}

## Textbooks:

There are no required textbooks for this course. All textbooks are free online or made available to you on Sakai.

- McKinney, *[Python for Data Analysis](https://wesmckinney.com/book/)*
- UW, *[Visualization Curriculum for Altair](https://idl.uw.edu/visualization-curriculum/intro.html)*
- Wilke, *[Fundamentals of Data Visualization](https://clauswilke.com/dataviz/)*
- Downey, *[Elements of Data Science](https://allendowney.github.io/ElementsOfDataScience/)*
- Bruce, Bruce, and Gedeck, *Practical Statistics for Data Scientists* 2nd ed.

### Note on the schedule

*Keep in mind that some of this schedule could change throughout the semester. However, if anything changes I'll update this page, and I'll be sure to give you plenty of advance notice.*

## Software

All projects in this course will be scripted and analyzed using Python, an open source programming language and environment. Specifically, we will be using JupyterHub as our programming environment. **No previous experience with Python, statistical software packages, or computer programming is required.**
